@startuml application_scheme
scale 800*800

interface "HTTP\HTTPS" as http

node "Rails приложение" {
  http -down- [ActionController]

  [Компонент управления заказами] as [order_control]
  [Компонент управления ВМ] as [vm_control]
  [Адаптер системы виртуализации] as [virt_adapter]
  [Компонент управления пользователями] as [user_control]
  [Компонент управления платежами] as [account_control]
  [Компонент тарификации заказов] as [order_tarification]
  [Компонент формирования отчёта] as [report_generator]
  [Компонент управления авторизацией] as [policy_control]
  [Адаптер платежной системы] as [bank_adapter]


  [order_control] ..> [ActionModel]
  [order_control] ..> [vm_control]

  [user_control] ..> [account_control]

  [user_control] ..> [ActionModel]
  [order_tarification] ..> [ActionModel]
  [report_generator] .down.> [ActionMailer]
  [report_generator] ..> [ActionModel]
  [vm_control] ..> [ActionModel]

  [ActionController] <-right-> [order_control]
  [ActionController] <-down-> [user_control]
  [ActionController] <---> [order_tarification]
  [ActionController] <---> [report_generator]
  [ActionController] <-right-> [policy_control]

  [vm_control] ..> [virt_adapter]
}

interface "Почтовый сервер" as mail_server
interface "Система виртуализации" as virt_system
interface "Платёжная система" as bank

account_control .down.> bank_adapter

bank_adapter --> bank

[ActionMailer] -down- mail_server
[ActionModel] -down- СУБД
[virt_adapter] -down- virt_system

@enduml