@startuml overview_components_diagram
scale 800*800

node "Прокси сервер" {
  [nginx]
}

database "Сервер БД" {
  [PostgreSQL]
}

node "Сервер виртуализации" {
  [OpenStack]
}

node "Почтовый сервер" {
  [Exim]
}

node "Сервер приложения" {
  [nginx] --> [Unicorn]
  [Unicorn] --> [Rails]
  [Rails] --> [Redis]
  [Sidekiq] --> [Redis]
  [Sidekiq] --> [Rails]
  [Rails] -right--> [PostgreSQL]
  [Rails] ---> [OpenStack]
  [Rails] --> [Exim]
}

@enduml
