@startuml overview_components_diagram
scale 800*800

node "Прокси сервер" {
  [nginx]
}

database "Сервер БД" {
  [PostgreSQL]
}

node "Сервер виртуализации" {
  [OpenStack]
}

node "Почтовый сервер" {
  [Exim]
}

node "Яндекс.Касса" {
  [JSON API] as json_api
}

node "Сервер приложения" {
  [nginx] --> [Unicorn]
  [Unicorn] --> [Rails]
  [Rails] --> [Redis]
  [Sidekiq] --> [Redis]
  [Sidekiq] --> [Rails]
  [Rails] -down-> [PostgreSQL]
  [Rails] -down-> [OpenStack]
  [Rails] -right-> [Exim]
  [Rails] -right-> json_api
}

@enduml
