@startuml report_request_usecase
scale 800*800

left to right direction

skinparam packageStyle rectangle

actor "Оператор" as clerk 

rectangle "Почтовый сервер" {
  (Отправка письма с файлом) as (EmailSending)
}

rectangle "Система" {
  (Запрос отчёта) as (ReportRequest)
  (Ввод данных) as (InfoInput)
  (Формирование отчёта) as (ReportFormating)
  (Сбор данных) as (ReportDataPreparation)
  (Генерация файла отчёта) as (ReportFilegeneration)
  (Отправка отчёта) as (ReportEmailSending)

  clerk -- (ReportRequest)

  (ReportRequest) .> (InfoInput)
  (InfoInput) .> (ReportFormating)
  (ReportFormating) .> (ReportDataPreparation)
  (ReportFormating) .> (ReportFilegeneration)
  (ReportFormating) .> (ReportEmailSending)

  (ReportEmailSending) .> (EmailSending)
}

@enduml
