@startuml virt_adapter_scheme
scale 800*800

node "Rails приложение" {
  node "Адаптер системы виртуализации" {
    [JSON API клиент] as http_client
  }
}

node "Система виртуализации" {
  interface "Сinder JSON API" as cinder_api
  ' note bottom of cinder_api
  '   Подсистема 
  '   работы с 
  '   дисками ВМ 
  ' end note 

  interface "Nova JSON API" as nova_api
  ' note bottom of nova_api
  '   Подсистема 
  '   работы с 
  '   инстансами ВМ
  ' end note

  interface "Neutron JSON API" as neutron_api
  ' note bottom of neutron_api
  '   Подсистема 
  '   работы с 
  '   сетью
  ' end note
}

http_client -down-> cinder_api
http_client -down-> nova_api
http_client -down-> neutron_api

@enduml